api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    # The title of the API.
    title: 'CRM'
    # The description of the API.
    description: 'Customers Relationship Management'
    # The version of the API.
    version: '0.0.0'
    collection:
        pagination:
            # To enable or disable pagination for all resource collections by default.
            enabled: false
            items_per_page: 5
            client_enabled: true
            client_items_per_page: true
            items_per_page_parameter_name: 'count'

